[package]
name = "pulsedcm-commands-ano"
version = "0.2.0"
description = "De-identification of DICOM files"
edition = "2021"

[dependencies]
pulsedcm-core = { path = "../../core" }
phf = { version = "0.13.1",  features = ["macros"] }
smallvec = "1.15.1"
